// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: proto/npu.proto

package npupb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConceptInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []float32 `protobuf:"fixed32,1,rep,packed,name=info,proto3" json:"info,omitempty"`
}

func (x *ConceptInfos) Reset() {
	*x = ConceptInfos{}
	mi := &file_proto_npu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptInfos) ProtoMessage() {}

func (x *ConceptInfos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptInfos.ProtoReflect.Descriptor instead.
func (*ConceptInfos) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{0}
}

func (x *ConceptInfos) GetInfo() []float32 {
	if x != nil {
		return x.Info
	}
	return nil
}

type ConceptDetectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyMap map[string]*ConceptInfos `protobuf:"bytes,1,rep,name=reply_map,json=replyMap,proto3" json:"reply_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ConceptDetectReply) Reset() {
	*x = ConceptDetectReply{}
	mi := &file_proto_npu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptDetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptDetectReply) ProtoMessage() {}

func (x *ConceptDetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptDetectReply.ProtoReflect.Descriptor instead.
func (*ConceptDetectReply) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{1}
}

func (x *ConceptDetectReply) GetReplyMap() map[string]*ConceptInfos {
	if x != nil {
		return x.ReplyMap
	}
	return nil
}

type FaceFeatureReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FaceFeature  []float32 `protobuf:"fixed32,1,rep,packed,name=face_feature,json=faceFeature,proto3" json:"face_feature,omitempty"`
	FeatureScore float32   `protobuf:"fixed32,2,opt,name=feature_score,json=featureScore,proto3" json:"feature_score,omitempty"`
}

func (x *FaceFeatureReply) Reset() {
	*x = FaceFeatureReply{}
	mi := &file_proto_npu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceFeatureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceFeatureReply) ProtoMessage() {}

func (x *FaceFeatureReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceFeatureReply.ProtoReflect.Descriptor instead.
func (*FaceFeatureReply) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{2}
}

func (x *FaceFeatureReply) GetFaceFeature() []float32 {
	if x != nil {
		return x.FaceFeature
	}
	return nil
}

func (x *FaceFeatureReply) GetFeatureScore() float32 {
	if x != nil {
		return x.FeatureScore
	}
	return 0
}

type FaceRect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X1         float32 `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1         float32 `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2         float32 `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2         float32 `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"`
	Confidance float32 `protobuf:"fixed32,5,opt,name=confidance,proto3" json:"confidance,omitempty"` // original spelling
}

func (x *FaceRect) Reset() {
	*x = FaceRect{}
	mi := &file_proto_npu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceRect) ProtoMessage() {}

func (x *FaceRect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceRect.ProtoReflect.Descriptor instead.
func (*FaceRect) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{3}
}

func (x *FaceRect) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *FaceRect) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *FaceRect) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *FaceRect) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *FaceRect) GetConfidance() float32 {
	if x != nil {
		return x.Confidance
	}
	return 0
}

type FaceLandmarks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X []float32 `protobuf:"fixed32,1,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y []float32 `protobuf:"fixed32,2,rep,packed,name=y,proto3" json:"y,omitempty"`
}

func (x *FaceLandmarks) Reset() {
	*x = FaceLandmarks{}
	mi := &file_proto_npu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceLandmarks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceLandmarks) ProtoMessage() {}

func (x *FaceLandmarks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceLandmarks.ProtoReflect.Descriptor instead.
func (*FaceLandmarks) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{4}
}

func (x *FaceLandmarks) GetX() []float32 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *FaceLandmarks) GetY() []float32 {
	if x != nil {
		return x.Y
	}
	return nil
}

type FaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bbox      *FaceRect      `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Landmarks *FaceLandmarks `protobuf:"bytes,2,opt,name=landmarks,proto3" json:"landmarks,omitempty"`
}

func (x *FaceInfo) Reset() {
	*x = FaceInfo{}
	mi := &file_proto_npu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceInfo) ProtoMessage() {}

func (x *FaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceInfo.ProtoReflect.Descriptor instead.
func (*FaceInfo) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{5}
}

func (x *FaceInfo) GetBbox() *FaceRect {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *FaceInfo) GetLandmarks() *FaceLandmarks {
	if x != nil {
		return x.Landmarks
	}
	return nil
}

type FaceDetectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FaceInfo []*FaceInfo `protobuf:"bytes,1,rep,name=face_info,json=faceInfo,proto3" json:"face_info,omitempty"`
}

func (x *FaceDetectReply) Reset() {
	*x = FaceDetectReply{}
	mi := &file_proto_npu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceDetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceDetectReply) ProtoMessage() {}

func (x *FaceDetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceDetectReply.ProtoReflect.Descriptor instead.
func (*FaceDetectReply) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{6}
}

func (x *FaceDetectReply) GetFaceInfo() []*FaceInfo {
	if x != nil {
		return x.FaceInfo
	}
	return nil
}

type CmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CmdRequest) Reset() {
	*x = CmdRequest{}
	mi := &file_proto_npu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRequest) ProtoMessage() {}

func (x *CmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRequest.ProtoReflect.Descriptor instead.
func (*CmdRequest) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{7}
}

func (x *CmdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CmdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CmdReply) Reset() {
	*x = CmdReply{}
	mi := &file_proto_npu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdReply) ProtoMessage() {}

func (x *CmdReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdReply.ProtoReflect.Descriptor instead.
func (*CmdReply) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{8}
}

func (x *CmdReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type BufferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buffer []byte `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *BufferRequest) Reset() {
	*x = BufferRequest{}
	mi := &file_proto_npu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferRequest) ProtoMessage() {}

func (x *BufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_npu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferRequest.ProtoReflect.Descriptor instead.
func (*BufferRequest) Descriptor() ([]byte, []int) {
	return file_proto_npu_proto_rawDescGZIP(), []int{9}
}

func (x *BufferRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

var File_proto_npu_proto protoreflect.FileDescriptor

var file_proto_npu_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x70, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6e, 0x70, 0x75, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x42, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65,
	0x70, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x4d, 0x61, 0x70, 0x1a, 0x4e, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x43, 0x6f,
	0x6e, 0x63, 0x65, 0x70, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5a, 0x0a, 0x10, 0x46, 0x61, 0x63, 0x65, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61, 0x63,
	0x65, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x0b, 0x66, 0x61, 0x63, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0c, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x22, 0x6a, 0x0a, 0x08, 0x46, 0x61, 0x63, 0x65, 0x52, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x78, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x79, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x79, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x78, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78, 0x32, 0x12, 0x0e, 0x0a,
	0x02, 0x79, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x79, 0x32, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x2b, 0x0a,
	0x0d, 0x46, 0x61, 0x63, 0x65, 0x4c, 0x61, 0x6e, 0x64, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x5f, 0x0a, 0x08, 0x46, 0x61,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x63, 0x74, 0x52, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x12, 0x30, 0x0a, 0x09, 0x6c, 0x61, 0x6e,
	0x64, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e,
	0x70, 0x75, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x4c, 0x61, 0x6e, 0x64, 0x6d, 0x61, 0x72, 0x6b, 0x73,
	0x52, 0x09, 0x6c, 0x61, 0x6e, 0x64, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x22, 0x3d, 0x0a, 0x0f, 0x46,
	0x61, 0x63, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a,
	0x0a, 0x09, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x20, 0x0a, 0x0a, 0x43, 0x6d,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x08,
	0x43, 0x6d, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x27, 0x0a, 0x0d, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x32, 0xf4, 0x01, 0x0a, 0x05, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x3c, 0x0a, 0x10, 0x46, 0x61, 0x63, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x42, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6e, 0x70,
	0x75, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3e, 0x0a, 0x11, 0x46, 0x61, 0x63, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x42, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x70, 0x75,
	0x2e, 0x46, 0x61, 0x63, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x42, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x42,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e,
	0x70, 0x75, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64,
	0x12, 0x0f, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x6e, 0x70, 0x75, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x58, 0x5a, 0x62, 0x2f, 0x72, 0x6b, 0x5f, 0x73, 0x79, 0x6e, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b,
	0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x6e, 0x70,
	0x75, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6e, 0x70, 0x75, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_npu_proto_rawDescOnce sync.Once
	file_proto_npu_proto_rawDescData = file_proto_npu_proto_rawDesc
)

func file_proto_npu_proto_rawDescGZIP() []byte {
	file_proto_npu_proto_rawDescOnce.Do(func() {
		file_proto_npu_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_npu_proto_rawDescData)
	})
	return file_proto_npu_proto_rawDescData
}

var file_proto_npu_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_npu_proto_goTypes = []any{
	(*ConceptInfos)(nil),       // 0: npu.ConceptInfos
	(*ConceptDetectReply)(nil), // 1: npu.ConceptDetectReply
	(*FaceFeatureReply)(nil),   // 2: npu.FaceFeatureReply
	(*FaceRect)(nil),           // 3: npu.FaceRect
	(*FaceLandmarks)(nil),      // 4: npu.FaceLandmarks
	(*FaceInfo)(nil),           // 5: npu.FaceInfo
	(*FaceDetectReply)(nil),    // 6: npu.FaceDetectReply
	(*CmdRequest)(nil),         // 7: npu.CmdRequest
	(*CmdReply)(nil),           // 8: npu.CmdReply
	(*BufferRequest)(nil),      // 9: npu.BufferRequest
	nil,                        // 10: npu.ConceptDetectReply.ReplyMapEntry
}
var file_proto_npu_proto_depIdxs = []int32{
	10, // 0: npu.ConceptDetectReply.reply_map:type_name -> npu.ConceptDetectReply.ReplyMapEntry
	3,  // 1: npu.FaceInfo.bbox:type_name -> npu.FaceRect
	4,  // 2: npu.FaceInfo.landmarks:type_name -> npu.FaceLandmarks
	5,  // 3: npu.FaceDetectReply.face_info:type_name -> npu.FaceInfo
	0,  // 4: npu.ConceptDetectReply.ReplyMapEntry.value:type_name -> npu.ConceptInfos
	9,  // 5: npu.Model.FaceDetectBuffer:input_type -> npu.BufferRequest
	9,  // 6: npu.Model.FaceFeatureBuffer:input_type -> npu.BufferRequest
	9,  // 7: npu.Model.ConceptDetectBuffer:input_type -> npu.BufferRequest
	7,  // 8: npu.Model.ExecCmd:input_type -> npu.CmdRequest
	6,  // 9: npu.Model.FaceDetectBuffer:output_type -> npu.FaceDetectReply
	2,  // 10: npu.Model.FaceFeatureBuffer:output_type -> npu.FaceFeatureReply
	1,  // 11: npu.Model.ConceptDetectBuffer:output_type -> npu.ConceptDetectReply
	8,  // 12: npu.Model.ExecCmd:output_type -> npu.CmdReply
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_npu_proto_init() }
func file_proto_npu_proto_init() {
	if File_proto_npu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_npu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_npu_proto_goTypes,
		DependencyIndexes: file_proto_npu_proto_depIdxs,
		MessageInfos:      file_proto_npu_proto_msgTypes,
	}.Build()
	File_proto_npu_proto = out.File
	file_proto_npu_proto_rawDesc = nil
	file_proto_npu_proto_goTypes = nil
	file_proto_npu_proto_depIdxs = nil
}
