// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/npu.proto

package npupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Model_FaceDetectBuffer_FullMethodName    = "/npu.Model/FaceDetectBuffer"
	Model_FaceFeatureBuffer_FullMethodName   = "/npu.Model/FaceFeatureBuffer"
	Model_ConceptDetectBuffer_FullMethodName = "/npu.Model/ConceptDetectBuffer"
	Model_ExecCmd_FullMethodName             = "/npu.Model/ExecCmd"
)

// ModelClient is the client API for Model service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelClient interface {
	FaceDetectBuffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*FaceDetectReply, error)
	FaceFeatureBuffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*FaceFeatureReply, error)
	ConceptDetectBuffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*ConceptDetectReply, error)
	ExecCmd(ctx context.Context, in *CmdRequest, opts ...grpc.CallOption) (*CmdReply, error)
}

type modelClient struct {
	cc grpc.ClientConnInterface
}

func NewModelClient(cc grpc.ClientConnInterface) ModelClient {
	return &modelClient{cc}
}

func (c *modelClient) FaceDetectBuffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*FaceDetectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FaceDetectReply)
	err := c.cc.Invoke(ctx, Model_FaceDetectBuffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) FaceFeatureBuffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*FaceFeatureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FaceFeatureReply)
	err := c.cc.Invoke(ctx, Model_FaceFeatureBuffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) ConceptDetectBuffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*ConceptDetectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConceptDetectReply)
	err := c.cc.Invoke(ctx, Model_ConceptDetectBuffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) ExecCmd(ctx context.Context, in *CmdRequest, opts ...grpc.CallOption) (*CmdReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmdReply)
	err := c.cc.Invoke(ctx, Model_ExecCmd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServer is the server API for Model service.
// All implementations must embed UnimplementedModelServer
// for forward compatibility.
type ModelServer interface {
	FaceDetectBuffer(context.Context, *BufferRequest) (*FaceDetectReply, error)
	FaceFeatureBuffer(context.Context, *BufferRequest) (*FaceFeatureReply, error)
	ConceptDetectBuffer(context.Context, *BufferRequest) (*ConceptDetectReply, error)
	ExecCmd(context.Context, *CmdRequest) (*CmdReply, error)
	mustEmbedUnimplementedModelServer()
}

// UnimplementedModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelServer struct{}

func (UnimplementedModelServer) FaceDetectBuffer(context.Context, *BufferRequest) (*FaceDetectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FaceDetectBuffer not implemented")
}
func (UnimplementedModelServer) FaceFeatureBuffer(context.Context, *BufferRequest) (*FaceFeatureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FaceFeatureBuffer not implemented")
}
func (UnimplementedModelServer) ConceptDetectBuffer(context.Context, *BufferRequest) (*ConceptDetectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConceptDetectBuffer not implemented")
}
func (UnimplementedModelServer) ExecCmd(context.Context, *CmdRequest) (*CmdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecCmd not implemented")
}
func (UnimplementedModelServer) mustEmbedUnimplementedModelServer() {}
func (UnimplementedModelServer) testEmbeddedByValue()               {}

// UnsafeModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServer will
// result in compilation errors.
type UnsafeModelServer interface {
	mustEmbedUnimplementedModelServer()
}

func RegisterModelServer(s grpc.ServiceRegistrar, srv ModelServer) {
	// If the following call pancis, it indicates UnimplementedModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Model_ServiceDesc, srv)
}

func _Model_FaceDetectBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BufferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).FaceDetectBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_FaceDetectBuffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).FaceDetectBuffer(ctx, req.(*BufferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_FaceFeatureBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BufferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).FaceFeatureBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_FaceFeatureBuffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).FaceFeatureBuffer(ctx, req.(*BufferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_ConceptDetectBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BufferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).ConceptDetectBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_ConceptDetectBuffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).ConceptDetectBuffer(ctx, req.(*BufferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_ExecCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).ExecCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_ExecCmd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).ExecCmd(ctx, req.(*CmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Model_ServiceDesc is the grpc.ServiceDesc for Model service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Model_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "npu.Model",
	HandlerType: (*ModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FaceDetectBuffer",
			Handler:    _Model_FaceDetectBuffer_Handler,
		},
		{
			MethodName: "FaceFeatureBuffer",
			Handler:    _Model_FaceFeatureBuffer_Handler,
		},
		{
			MethodName: "ConceptDetectBuffer",
			Handler:    _Model_ConceptDetectBuffer_Handler,
		},
		{
			MethodName: "ExecCmd",
			Handler:    _Model_ExecCmd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/npu.proto",
}
